openapi: 3.0.0
info:
  title: 'Test API'
  version: '0.1'
paths:
  /v1/test:
    get:
      description: 'test api'
      operationId: 'Controller\Test::select'
      responses:
        default:
          description: 'Welcome page'
